[2020-12-22 15:52:26] [INFO]	-- Start ShortestPathTest
[2020-12-22 15:52:28] [DEBUG]		1	Schedule: 1.00%	Time: 2s 105ms 542us 319ns	Sample: [586, 19489341]	Result Path Length 1
[2020-12-22 15:52:31] [DEBUG]		2	Schedule: 2.00%	Time: 2s 200ms 165us 38ns	Sample: [12, 34693000]	Result Path Length 2
[2020-12-22 15:53:33] [ERROR]	There was an error executing item 3!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 15:53:33] [DEBUG]		3	Schedule: 3.00%	Time: 1m 2s 271ms 560us 703ns	Sample: [12, 38996376]	Result Execute error.
[2020-12-22 15:54:42] [ERROR]	There was an error executing item 4!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 15:54:42] [DEBUG]		4	Schedule: 4.00%	Time: 1m 9s 326ms 442us 665ns	Sample: [7846, 16452172]	Result Execute error.
[2020-12-22 15:55:43] [ERROR]	There was an error executing item 5!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 15:55:43] [DEBUG]		5	Schedule: 5.00%	Time: 1m 1s 126ms 432us 487ns	Sample: [1116721, 30476884]	Result Execute error.
[2020-12-22 15:56:04] [DEBUG]		6	Schedule: 6.00%	Time: 20s 532ms 132us 489ns	Sample: [428333, 39105685]	Result Path Length 1
[2020-12-22 15:56:06] [DEBUG]		7	Schedule: 7.00%	Time: 2s 225ms 434us 447ns	Sample: [12, 14662891]	Result Path Length 2
[2020-12-22 15:57:08] [ERROR]	There was an error executing item 8!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 15:57:08] [DEBUG]		8	Schedule: 8.00%	Time: 1m 2s 249ms 890us 915ns	Sample: [12, 39211668]	Result Execute error.
[2020-12-22 15:58:16] [ERROR]	There was an error executing item 9!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 15:58:16] [DEBUG]		9	Schedule: 9.00%	Time: 1m 7s 692ms 711us 357ns	Sample: [10350, 44558906]	Result Execute error.
[2020-12-22 15:59:16] [ERROR]	There was an error executing item 10!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 15:59:16] [DEBUG]		10	Schedule: 10.00%	Time: 1m 0s 11ms 670us 434ns	Sample: [1441581, 60215794]	Result Execute error.
[2020-12-22 16:00:16] [ERROR]	There was an error executing item 11!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:00:16] [DEBUG]		11	Schedule: 11.00%	Time: 1m 0s 10ms 283us 978ns	Sample: [428333, 34645851]	Result Execute error.
[2020-12-22 16:01:16] [ERROR]	There was an error executing item 12!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:01:16] [DEBUG]		12	Schedule: 12.00%	Time: 1m 0s 12ms 135us 142ns	Sample: [12, 20747008]	Result Execute error.
[2020-12-22 16:02:16] [ERROR]	There was an error executing item 13!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:02:16] [DEBUG]		13	Schedule: 13.00%	Time: 1m 0s 9ms 202us 102ns	Sample: [12, 46703729]	Result Execute error.
[2020-12-22 16:03:16] [ERROR]	There was an error executing item 14!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:03:16] [DEBUG]		14	Schedule: 14.00%	Time: 1m 0s 12ms 755us 211ns	Sample: [13568, 23785000]	Result Execute error.
[2020-12-22 16:04:16] [ERROR]	There was an error executing item 15!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:04:16] [DEBUG]		15	Schedule: 15.00%	Time: 1m 0s 12ms 546us 837ns	Sample: [2998231, 51994999]	Result Execute error.
[2020-12-22 16:05:16] [ERROR]	There was an error executing item 16!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:05:16] [DEBUG]		16	Schedule: 16.00%	Time: 59s 999ms 392us 473ns	Sample: [657863, 49959175]	Result Execute error.
[2020-12-22 16:06:16] [ERROR]	There was an error executing item 17!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:06:16] [DEBUG]		17	Schedule: 17.00%	Time: 1m 0s 10ms 3us 28ns	Sample: [12, 59090097]	Result Execute error.
[2020-12-22 16:07:16] [ERROR]	There was an error executing item 18!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:07:16] [DEBUG]		18	Schedule: 18.00%	Time: 59s 999ms 172us 255ns	Sample: [13, 48506788]	Result Execute error.
[2020-12-22 16:08:16] [ERROR]	There was an error executing item 19!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:08:16] [DEBUG]		19	Schedule: 19.00%	Time: 1m 0s 5ms 168us 858ns	Sample: [13568, 40984309]	Result Execute error.
[2020-12-22 16:09:16] [ERROR]	There was an error executing item 20!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:09:16] [DEBUG]		20	Schedule: 20.00%	Time: 1m 0s 8ms 508us 629ns	Sample: [5479972, 49846982]	Result Execute error.
[2020-12-22 16:10:16] [ERROR]	There was an error executing item 21!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:10:16] [DEBUG]		21	Schedule: 21.00%	Time: 1m 0s 12ms 325us 731ns	Sample: [734493, 34693000]	Result Execute error.
[2020-12-22 16:11:16] [ERROR]	There was an error executing item 22!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:11:16] [DEBUG]		22	Schedule: 22.00%	Time: 1m 0s 11ms 435us 542ns	Sample: [12, 36575605]	Result Execute error.
[2020-12-22 16:12:16] [ERROR]	There was an error executing item 23!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:12:16] [DEBUG]		23	Schedule: 23.00%	Time: 1m 0s 11ms 970us 199ns	Sample: [13, 40337603]	Result Execute error.
[2020-12-22 16:13:16] [ERROR]	There was an error executing item 24!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:13:16] [DEBUG]		24	Schedule: 24.00%	Time: 1m 0s 9ms 719us 648ns	Sample: [38073, 40045004]	Result Execute error.
[2020-12-22 16:14:16] [ERROR]	There was an error executing item 25!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:14:16] [DEBUG]		25	Schedule: 25.00%	Time: 1m 0s 9ms 530us 821ns	Sample: [5679002, 48979211]	Result Execute error.
[2020-12-22 16:15:16] [ERROR]	There was an error executing item 26!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:15:16] [DEBUG]		26	Schedule: 26.00%	Time: 1m 0s 6ms 5us 780ns	Sample: [783214, 34693000]	Result Execute error.
[2020-12-22 16:16:16] [ERROR]	There was an error executing item 27!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:16:16] [DEBUG]		27	Schedule: 27.00%	Time: 1m 0s 8ms 66us 833ns	Sample: [13, 34693000]	Result Execute error.
[2020-12-22 16:17:16] [ERROR]	There was an error executing item 28!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:17:16] [DEBUG]		28	Schedule: 28.00%	Time: 1m 0s 2ms 232us 50ns	Sample: [20, 26526108]	Result Execute error.
[2020-12-22 16:18:16] [ERROR]	There was an error executing item 29!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:18:16] [DEBUG]		29	Schedule: 29.00%	Time: 1m 0s 11ms 483us 359ns	Sample: [38073, 46575047]	Result Execute error.
[2020-12-22 16:19:16] [ERROR]	There was an error executing item 30!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:19:16] [DEBUG]		30	Schedule: 30.00%	Time: 1m 0s 12ms 284us 753ns	Sample: [5679002, 38814278]	Result Execute error.
[2020-12-22 16:20:16] [ERROR]	There was an error executing item 31!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:20:16] [DEBUG]		31	Schedule: 31.00%	Time: 1m 0s 1ms 857us 527ns	Sample: [783214, 34693000]	Result Execute error.
[2020-12-22 16:21:16] [ERROR]	There was an error executing item 32!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:21:16] [DEBUG]		32	Schedule: 32.00%	Time: 1m 0s 4ms 573us 476ns	Sample: [13, 52690507]	Result Execute error.
[2020-12-22 16:22:16] [ERROR]	There was an error executing item 33!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:22:16] [DEBUG]		33	Schedule: 33.00%	Time: 1m 0s 9ms 887us 683ns	Sample: [291, 35177446]	Result Execute error.
[2020-12-22 16:23:16] [ERROR]	There was an error executing item 34!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:23:16] [DEBUG]		34	Schedule: 34.00%	Time: 1m 0s 10ms 785us 988ns	Sample: [77973, 35540389]	Result Execute error.
[2020-12-22 16:24:16] [ERROR]	There was an error executing item 35!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:24:16] [DEBUG]		35	Schedule: 35.00%	Time: 1m 0s 14ms 982us 303ns	Sample: [5679002, 44634414]	Result Execute error.
[2020-12-22 16:25:16] [ERROR]	There was an error executing item 36!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:25:16] [DEBUG]		36	Schedule: 36.00%	Time: 1m 0s 10ms 793us 225ns	Sample: [807095, 20235373]	Result Execute error.
[2020-12-22 16:26:16] [ERROR]	There was an error executing item 37!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:26:16] [DEBUG]		37	Schedule: 37.00%	Time: 1m 0s 3ms 292us 18ns	Sample: [13, 15759590]	Result Execute error.
[2020-12-22 16:27:16] [ERROR]	There was an error executing item 38!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:27:16] [DEBUG]		38	Schedule: 38.00%	Time: 1m 0s 11ms 176us 275ns	Sample: [291, 16132610]	Result Execute error.
[2020-12-22 16:28:16] [ERROR]	There was an error executing item 39!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:28:16] [DEBUG]		39	Schedule: 39.00%	Time: 1m 0s 10ms 755us 118ns	Sample: [77973, 22752200]	Result Execute error.
[2020-12-22 16:29:16] [ERROR]	There was an error executing item 40!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:29:16] [DEBUG]		40	Schedule: 40.00%	Time: 1m 0s 11ms 170us 282ns	Sample: [5860132, 20988664]	Result Execute error.
[2020-12-22 16:30:16] [ERROR]	There was an error executing item 41!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:30:16] [DEBUG]		41	Schedule: 41.00%	Time: 1m 0s 10ms 844us 60ns	Sample: [813286, 24185375]	Result Execute error.
[2020-12-22 16:31:16] [ERROR]	There was an error executing item 42!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:31:16] [DEBUG]		42	Schedule: 42.00%	Time: 1m 0s 3ms 684us 783ns	Sample: [20, 34693000]	Result Execute error.
[2020-12-22 16:32:16] [ERROR]	There was an error executing item 43!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:32:16] [DEBUG]		43	Schedule: 43.00%	Time: 1m 0s 8ms 618us 703ns	Sample: [291, 26680462]	Result Execute error.
[2020-12-22 16:33:16] [ERROR]	There was an error executing item 44!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:33:16] [DEBUG]		44	Schedule: 44.00%	Time: 1m 0s 9ms 827us 342ns	Sample: [428333, 25456524]	Result Execute error.
[2020-12-22 16:34:16] [ERROR]	There was an error executing item 45!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:34:16] [DEBUG]		45	Schedule: 45.00%	Time: 1m 0s 11ms 728us 650ns	Sample: [6073282, 32064738]	Result Execute error.
[2020-12-22 16:35:16] [ERROR]	There was an error executing item 46!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:35:16] [DEBUG]		46	Schedule: 46.00%	Time: 1m 0s 18ms 238us 256ns	Sample: [816653, 28429668]	Result Execute error.
[2020-12-22 16:36:16] [ERROR]	There was an error executing item 47!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:36:16] [DEBUG]		47	Schedule: 47.00%	Time: 1m 0s 11ms 406us 374ns	Sample: [20, 43017418]	Result Execute error.
[2020-12-22 16:37:16] [ERROR]	There was an error executing item 48!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:37:16] [DEBUG]		48	Schedule: 48.00%	Time: 1m 0s 8ms 747us 388ns	Sample: [291, 17178680]	Result Execute error.
[2020-12-22 16:38:16] [ERROR]	There was an error executing item 49!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:38:16] [DEBUG]		49	Schedule: 49.00%	Time: 1m 0s 9ms 317us 402ns	Sample: [651583, 37781038]	Result Execute error.
[2020-12-22 16:39:16] [ERROR]	There was an error executing item 50!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:39:16] [DEBUG]		50	Schedule: 50.00%	Time: 1m 0s 3ms 235us 428ns	Sample: [6352582, 23397450]	Result Execute error.
[2020-12-22 16:40:16] [ERROR]	There was an error executing item 51!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:40:16] [DEBUG]		51	Schedule: 51.00%	Time: 1m 0s 10ms 432us 816ns	Sample: [8841372, 34693000]	Result Execute error.
[2020-12-22 16:41:16] [ERROR]	There was an error executing item 52!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:41:16] [DEBUG]		52	Schedule: 52.00%	Time: 1m 0s 11ms 819us 843ns	Sample: [20, 60903343]	Result Execute error.
[2020-12-22 16:42:17] [ERROR]	There was an error executing item 53!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:42:17] [DEBUG]		53	Schedule: 53.00%	Time: 1m 0s 14ms 669us 362ns	Sample: [291, 52047484]	Result Execute error.
[2020-12-22 16:43:17] [ERROR]	There was an error executing item 54!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:43:17] [DEBUG]		54	Schedule: 54.00%	Time: 1m 0s 10ms 810us 417ns	Sample: [651583, 50364443]	Result Execute error.
[2020-12-22 16:44:17] [ERROR]	There was an error executing item 55!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:44:17] [DEBUG]		55	Schedule: 55.00%	Time: 1m 0s 9ms 350us 472ns	Sample: [6515122, 30961549]	Result Execute error.
[2020-12-22 16:45:17] [ERROR]	There was an error executing item 56!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:45:17] [DEBUG]		56	Schedule: 56.00%	Time: 1m 0s 49ms 254us 54ns	Sample: [14089195, 30977642]	Result Execute error.
[2020-12-22 16:46:17] [ERROR]	There was an error executing item 57!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:46:17] [DEBUG]		57	Schedule: 57.00%	Time: 1m 0s 15ms 514us 246ns	Sample: [20, 18769019]	Result Execute error.
[2020-12-22 16:47:17] [ERROR]	There was an error executing item 58!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:47:17] [DEBUG]		58	Schedule: 58.00%	Time: 1m 0s 10ms 847us 314ns	Sample: [291, 45842727]	Result Execute error.
[2020-12-22 16:48:17] [ERROR]	There was an error executing item 59!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:48:17] [DEBUG]		59	Schedule: 59.00%	Time: 1m 0s 20ms 150us 486ns	Sample: [657863, 48525811]	Result Execute error.
[2020-12-22 16:49:17] [ERROR]	There was an error executing item 60!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:49:17] [DEBUG]		60	Schedule: 60.00%	Time: 1m 0s 13ms 357us 423ns	Sample: [6616312, 31381117]	Result Execute error.
[2020-12-22 16:50:17] [ERROR]	There was an error executing item 61!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:50:17] [DEBUG]		61	Schedule: 61.00%	Time: 59s 999ms 258us 438ns	Sample: [14094741, 34693000]	Result Execute error.
[2020-12-22 16:51:17] [ERROR]	There was an error executing item 62!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:51:17] [DEBUG]		62	Schedule: 62.00%	Time: 1m 0s 5ms 506us 134ns	Sample: [20, 40538952]	Result Execute error.
[2020-12-22 16:52:17] [ERROR]	There was an error executing item 63!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:52:17] [DEBUG]		63	Schedule: 63.00%	Time: 1m 0s 9ms 306us 526ns	Sample: [586, 24435102]	Result Execute error.
[2020-12-22 16:53:17] [ERROR]	There was an error executing item 64!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:53:17] [DEBUG]		64	Schedule: 64.00%	Time: 1m 0s 11ms 134us 545ns	Sample: [657863, 29249621]	Result Execute error.
[2020-12-22 16:54:17] [ERROR]	There was an error executing item 65!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:54:17] [DEBUG]		65	Schedule: 65.00%	Time: 1m 0s 11ms 225us 803ns	Sample: [6616312, 38253739]	Result Execute error.
[2020-12-22 16:55:17] [ERROR]	There was an error executing item 66!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:55:17] [DEBUG]		66	Schedule: 66.00%	Time: 1m 0s 10ms 193us 58ns	Sample: [14094741, 27625585]	Result Execute error.
[2020-12-22 16:56:17] [ERROR]	There was an error executing item 67!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:56:17] [DEBUG]		67	Schedule: 67.00%	Time: 1m 0s 7ms 625us 90ns	Sample: [20, 35549219]	Result Execute error.
[2020-12-22 16:57:17] [ERROR]	There was an error executing item 68!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:57:17] [DEBUG]		68	Schedule: 68.00%	Time: 1m 0s 10ms 817us 583ns	Sample: [586, 18956946]	Result Execute error.
[2020-12-22 16:58:17] [ERROR]	There was an error executing item 69!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:58:17] [DEBUG]		69	Schedule: 69.00%	Time: 1m 0s 13ms 948us 966ns	Sample: [734493, 55525978]	Result Execute error.
[2020-12-22 16:59:17] [ERROR]	There was an error executing item 70!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 16:59:17] [DEBUG]		70	Schedule: 70.00%	Time: 1m 0s 11ms 203us 76ns	Sample: [6616312, 51775754]	Result Execute error.
[2020-12-22 17:00:17] [ERROR]	There was an error executing item 71!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:00:17] [DEBUG]		71	Schedule: 71.00%	Time: 1m 0s 4ms 620us 646ns	Sample: [14178674, 56053555]	Result Execute error.
[2020-12-22 17:01:17] [ERROR]	There was an error executing item 72!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:01:17] [DEBUG]		72	Schedule: 72.00%	Time: 1m 0s 11ms 439us 431ns	Sample: [291, 34693000]	Result Execute error.
[2020-12-22 17:02:17] [ERROR]	There was an error executing item 73!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:02:17] [DEBUG]		73	Schedule: 73.00%	Time: 1m 0s 10ms 531us 303ns	Sample: [586, 22316351]	Result Execute error.
[2020-12-22 17:03:17] [ERROR]	There was an error executing item 74!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:03:17] [DEBUG]		74	Schedule: 74.00%	Time: 1m 0s 8ms 397us 423ns	Sample: [734493, 59142474]	Result Execute error.
[2020-12-22 17:04:17] [ERROR]	There was an error executing item 75!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:04:17] [DEBUG]		75	Schedule: 75.00%	Time: 1m 0s 5ms 727us 861ns	Sample: [6616312, 19124865]	Result Execute error.
[2020-12-22 17:05:17] [ERROR]	There was an error executing item 76!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:05:17] [DEBUG]		76	Schedule: 76.00%	Time: 1m 0s 12ms 828us 93ns	Sample: [14506253, 51595078]	Result Execute error.
[2020-12-22 17:06:17] [ERROR]	There was an error executing item 77!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:06:17] [DEBUG]		77	Schedule: 77.00%	Time: 1m 0s 9ms 526us 933ns	Sample: [291, 26953644]	Result Execute error.
[2020-12-22 17:07:17] [ERROR]	There was an error executing item 78!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:07:17] [DEBUG]		78	Schedule: 78.00%	Time: 1m 0s 10ms 806us 604ns	Sample: [586, 45072588]	Result Execute error.
[2020-12-22 17:08:17] [ERROR]	There was an error executing item 79!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:08:17] [DEBUG]		79	Schedule: 79.00%	Time: 1m 0s 11ms 138us 357ns	Sample: [734753, 19728462]	Result Execute error.
[2020-12-22 17:09:17] [ERROR]	There was an error executing item 80!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:09:17] [DEBUG]		80	Schedule: 80.00%	Time: 1m 0s 3ms 425us 199ns	Sample: [6741632, 12218912]	Result Execute error.
[2020-12-22 17:10:17] [ERROR]	There was an error executing item 81!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:10:17] [DEBUG]		81	Schedule: 81.00%	Time: 1m 0s 10ms 856us 509ns	Sample: [14515734, 28942591]	Result Execute error.
[2020-12-22 17:11:17] [ERROR]	There was an error executing item 82!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:11:17] [DEBUG]		82	Schedule: 82.00%	Time: 1m 0s 15ms 619us 408ns	Sample: [586, 34693000]	Result Execute error.
[2020-12-22 17:12:17] [ERROR]	There was an error executing item 83!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:12:17] [DEBUG]		83	Schedule: 83.00%	Time: 1m 0s 11ms 114us 512ns	Sample: [586, 30155163]	Result Execute error.
[2020-12-22 17:13:17] [ERROR]	There was an error executing item 84!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:13:17] [DEBUG]		84	Schedule: 84.00%	Time: 1m 0s 12ms 522us 97ns	Sample: [734753, 40142698]	Result Execute error.
[2020-12-22 17:14:17] [ERROR]	There was an error executing item 85!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:14:17] [DEBUG]		85	Schedule: 85.00%	Time: 1m 0s 10ms 855us 946ns	Sample: [7006772, 43603432]	Result Execute error.
[2020-12-22 17:15:17] [ERROR]	There was an error executing item 86!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:15:17] [DEBUG]		86	Schedule: 86.00%	Time: 1m 0s 9ms 525us 396ns	Sample: [14575107, 21219777]	Result Execute error.
[2020-12-22 17:16:17] [ERROR]	There was an error executing item 87!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:16:17] [DEBUG]		87	Schedule: 87.00%	Time: 1m 0s 13ms 394us 610ns	Sample: [586, 37870063]	Result Execute error.
[2020-12-22 17:17:17] [ERROR]	There was an error executing item 88!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:17:17] [DEBUG]		88	Schedule: 88.00%	Time: 1m 0s 8ms 763us 856ns	Sample: [989, 47382300]	Result Execute error.
[2020-12-22 17:18:17] [ERROR]	There was an error executing item 89!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:18:17] [DEBUG]		89	Schedule: 89.00%	Time: 1m 0s 13ms 345us 868ns	Sample: [734753, 17916412]	Result Execute error.
[2020-12-22 17:19:17] [ERROR]	There was an error executing item 90!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:19:17] [DEBUG]		90	Schedule: 90.00%	Time: 1m 0s 9ms 47us 771ns	Sample: [7614292, 14544383]	Result Execute error.
[2020-12-22 17:20:17] [ERROR]	There was an error executing item 91!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:20:17] [DEBUG]		91	Schedule: 91.00%	Time: 1m 0s 11ms 361us 842ns	Sample: [14934818, 34693000]	Result Execute error.
[2020-12-22 17:21:17] [ERROR]	There was an error executing item 92!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:21:17] [DEBUG]		92	Schedule: 92.00%	Time: 1m 0s 9ms 117us 214ns	Sample: [586, 50816298]	Result Execute error.
[2020-12-22 17:22:17] [ERROR]	There was an error executing item 93!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:22:17] [DEBUG]		93	Schedule: 93.00%	Time: 1m 0s 12ms 536us 112ns	Sample: [3475, 43501582]	Result Execute error.
[2020-12-22 17:23:17] [ERROR]	There was an error executing item 94!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:23:17] [DEBUG]		94	Schedule: 94.00%	Time: 1m 0s 11ms 832us 640ns	Sample: [756417, 25730640]	Result Execute error.
[2020-12-22 17:24:17] [ERROR]	There was an error executing item 95!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:24:17] [DEBUG]		95	Schedule: 95.00%	Time: 1m 0s 11ms 249us 957ns	Sample: [9077472, 39114112]	Result Execute error.
[2020-12-22 17:25:17] [ERROR]	There was an error executing item 96!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:25:17] [DEBUG]		96	Schedule: 96.00%	Time: 1m 0s 10ms 600us 885ns	Sample: [15076390, 34693000]	Result Execute error.
[2020-12-22 17:26:17] [ERROR]	There was an error executing item 97!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:26:17] [DEBUG]		97	Schedule: 97.00%	Time: 1m 0s 7ms 726us 826ns	Sample: [989, 34693000]	Result Execute error.
[2020-12-22 17:27:17] [ERROR]	There was an error executing item 98!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:27:17] [DEBUG]		98	Schedule: 98.00%	Time: 1m 0s 12ms 641us 482ns	Sample: [3475, 48368793]	Result Execute error.
[2020-12-22 17:28:17] [ERROR]	There was an error executing item 99!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:28:17] [DEBUG]		99	Schedule: 99.00%	Time: 1m 0s 12ms 796us 161ns	Sample: [756417, 41361187]	Result Execute error.
[2020-12-22 17:29:17] [ERROR]	There was an error executing item 100!
java.util.concurrent.ExecutionException: com.vesoft.nebula.client.graph.NGQLException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.galaxybase.benchmark.common.test.AbstractTest.testFinish(AbstractTest.java:126)
	at com.galaxybase.benchmark.common.test.AbstractTest.startTest(AbstractTest.java:94)
	at com.galaxybase.benchmark.common.util.TestManager.doStartTest(TestManager.java:60)
	at com.galaxybase.benchmark.common.util.TestManager.startTest(TestManager.java:25)
	at com.galaxybase.benchmark.nebula.AutoMain.main(AutoMain.java:11)
Caused by: com.vesoft.nebula.client.graph.NGQLException
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:135)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:24)
	at com.galaxybase.benchmark.nebula.test.util.NebulaTest.onStartTest(NebulaTest.java:12)
	at com.galaxybase.benchmark.common.test.AbstractTest$1.run(AbstractTest.java:85)
	at com.galaxybase.benchmark.common.test.AbstractTest$TaskCallable.call(AbstractTest.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-12-22 17:29:17] [DEBUG]		100	Schedule: 100.00%	Time: 1m 0s 7ms 197us 760ns	Sample: [10337242, 22168844]	Result Execute error.
[2020-12-22 17:29:17] [INFO]	-- Result Statistics
[2020-12-22 17:29:17] [INFO]	minTime: 2s 105ms 542us 319ns(2105.54ms)
[2020-12-22 17:29:17] [INFO]	maxTime: 20s 532ms 132us 489ns(20532.13ms)
[2020-12-22 17:29:17] [INFO]	AvgTime: 6s 765ms 818us 573ns(6765.82ms)
[2020-12-22 17:29:17] [INFO]	P99: 19s 982ms 931us 547ns(19982.93ms)
[2020-12-22 17:29:17] [INFO]	P999: 20s 477ms 212us 394ns(20477.21ms)
[2020-12-22 17:29:17] [INFO]	Throughput: 0.00
[2020-12-22 17:29:17] [INFO]	SuccessNum: 4
[2020-12-22 17:29:17] [INFO]	SuccessRate: 4.00%
[2020-12-22 17:29:17] [INFO]	ErrorNum: 96
[2020-12-22 17:29:17] [INFO]	ErrorRate: 96.00%
[2020-12-22 17:29:17] [INFO]	TimeoutNum: 0
[2020-12-22 17:29:17] [INFO]	TimeoutRate: 0.00%
[2020-12-22 17:29:17] [INFO]	PathLength Average: 1.50
[2020-12-22 17:29:17] [INFO]	-- End ShortestPathTest